// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Daniel Snider

import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import prettier from 'eslint-config-prettier';
import svelteConfig from './svelte.config.js';

const SVELTE = ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'];

// Mirrors .svelte-kit/tsconfig.json's `include`, so it is exactly the files that carry type
// information -- including the .js kinds, which allowJs+checkJs put in the program too. Everything
// else is handled as this set's complement rather than a second list, so the two always partition
// the repo along the same line the program does. Keep it in step with that include; #132 is the
// issue that moves e2e/ into the program.
const TYPED = [
  'src/**/*.{js,ts,svelte}',
  'test/**/*.{js,ts,svelte}',
  'tests/**/*.{js,ts,svelte}',
  'vite.config.{js,ts}'
];

// The other half of that mirror: tsconfig's `exclude`. SvelteKit builds the service worker in a
// program of its own, so these live under src/ but not in ours -- and projectService fails a file
// it cannot find outright, so they have to come back out of TYPED.
const NOT_TYPED = [
  'src/service-worker.{js,ts}',
  'src/service-worker.d.ts',
  'src/service-worker/**/*.{js,ts}'
];

// No published header plugin can enforce this on components, because svelte-eslint-parser drops
// comments that sit outside <script>/<style> and so never reports the <!-- --> form.
const spdxHeader = {
  meta: {
    type: 'problem',
    docs: { description: 'require the two-line SPDX header from CONTRIBUTING.md' },
    schema: []
  },
  create(context) {
    return {
      Program(node) {
        // Four lines, not one, because a shebang legitimately precedes the header.
        const head = context.sourceCode.getText().split('\n').slice(0, 4).join('\n');
        const svelteFile = context.filename.endsWith('.svelte');
        const license = svelteFile
          ? /^<!-- SPDX-License-Identifier: AGPL-3\.0-or-later -->$/m
          : /^\/\/ SPDX-License-Identifier: AGPL-3\.0-or-later$/m;
        const copyright = svelteFile
          ? /^<!-- Copyright \(C\) \d{4} .+ -->$/m
          : /^\/\/ Copyright \(C\) \d{4} .+$/m;
        if (!license.test(head) || !copyright.test(head)) {
          context.report({
            node,
            message:
              'Missing the two-line SPDX header (CONTRIBUTING.md); components use the <!-- --> form.'
          });
        }
      }
    };
  }
};

export default defineConfig(
  // Flat config ignores only node_modules and .git by default, and reads no gitignore at all, so
  // .claude/ -- two live worktrees excluded merely by .git/info/exclude -- has to be named here.
  globalIgnores([
    '.claude/**',
    '.svelte-kit/**',
    'build/**',
    'build-recorder/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    '.playwright/**',
    '.playwright-mcp/**',
    '.pnpm-cache/**',
    '.pnpm-data/**',
    '.pnpm-state/**',
    'data/**',
    'static/**',
    // Generated: an esbuild bundle whose own header says do not edit.
    'design/mission-control/support.js',
    // Regenerated by scripts/sanitize-fixture.mjs on every capture.
    'e2e/fixtures/live-snapshot.ts'
  ]),

  js.configs.recommended,
  // Its rule block carries no `files` key, so all 43 rules land everywhere and the 27 type-aware
  // ones would throw outside the program -- the complement block near the bottom is what scopes
  // them, and is load-bearing rather than belt-and-braces because of this line.
  ts.configs.recommendedTypeChecked,

  // Scoped, because the preset puts no `files` key on its rule block and would otherwise run all
  // 35 svelte/* rules against plain .ts as well.
  { files: SVELTE, extends: [svelte.configs.recommended, svelte.configs.prettier] },

  {
    languageOptions: { globals: { ...globals.browser, ...globals.node } }
  },

  {
    files: SVELTE,
    languageOptions: {
      parserOptions: { parser: ts.parser, extraFileExtensions: ['.svelte'], svelteConfig }
    }
  },

  {
    // Scoped to TYPED, and never wider -- not even to all .svelte. The parser fails a file it
    // cannot find in the project outright rather than degrading, so a component added anywhere
    // outside src/ would report `Parsing error: ... not found by the project service` instead of
    // simply going un-type-checked.
    //
    // This also makes ESLint depend on `svelte-kit sync` output: without .svelte-kit/tsconfig.json
    // every import resolves to an error type and a single file reports ~111 phantom `no-unsafe-*`.
    // `pnpm lint` syncs first; a bare `eslint` or an editor's LSP on a fresh clone does not.
    files: TYPED,
    ignores: NOT_TYPED,
    languageOptions: { parserOptions: { projectService: true } }
  },

  {
    // typescript-eslint's own eslint-recommended block is scoped to .ts and never reaches .svelte,
    // so the core rules TypeScript already covers stay on across 12,787 lines of components.
    files: SVELTE,
    rules: {
      'constructor-super': 'off',
      'getter-return': 'off',
      'no-class-assign': 'off',
      'no-const-assign': 'off',
      'no-dupe-args': 'off',
      'no-dupe-class-members': 'off',
      'no-dupe-keys': 'off',
      'no-func-assign': 'off',
      'no-import-assign': 'off',
      'no-new-native-nonconstructor': 'off',
      'no-obj-calls': 'off',
      'no-redeclare': 'off',
      'no-setter-return': 'off',
      'no-this-before-super': 'off',
      'no-undef': 'off',
      'no-unreachable': 'off',
      'no-unsafe-negation': 'off',
      'no-with': 'off',
      // Not the core rule: it would tell you to make a never-reassigned `let x = $state(0)` const.
      'svelte/prefer-const': [
        'error',
        { excludedRunes: ['$props', '$derived', '$state', '$bindable'] }
      ]
    }
  },

  {
    // AGENTS.md's Svelte 5 guardrail is prose only, and eslint-plugin-svelte has no rule for these
    // three. `export let` and `$:` are compile errors under `runes: true`; bare-let is only the
    // `non_reactive_update` warning, which is why `check` runs with --fail-on-warnings.
    files: SVELTE,
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "SvelteDirective[kind='EventHandler']",
          message: 'Svelte 4 event directive. Use the onclick={fn} attribute form (AGENTS.md).'
        },
        {
          selector: "SvelteElement[name.name='slot']",
          message: 'Svelte 4 slot. Use {#snippet} + {@render children()} (AGENTS.md).'
        }
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'svelte',
              importNames: ['createEventDispatcher'],
              message: 'Svelte 4 component events. Use callback props (AGENTS.md).'
            }
          ]
        }
      ],
      // Both ship as warnings and both measure zero, so promoting them keeps the config warning-free.
      'svelte/no-at-debug-tags': 'error',
      'svelte/no-inspect': 'error',
      // Every link here is a correct root-relative literal and no kit.paths.base is configured.
      'svelte/no-navigation-without-resolve': 'off',
      // Checks mutability alone, with no notion of reactive scope, so it flags function-local
      // scratch Maps and Sets that are rebuilt per call and never held as state.
      'svelte/prefer-svelte-reactivity': 'off',
      // A `{' x '}` literal is how you pin whitespace that Prettier's re-wrapping would otherwise
      // move into an indent, so the mustache the rule calls useless is load-bearing.
      'svelte/no-useless-mustaches': 'off'
    }
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
      ]
    }
  },

  {
    // Strict-tier rules worth their measured cost here. Scoped, never universal: every one calls
    // getParserServices, which throws rather than degrading when a file has no type information.
    // The recommendedTypeChecked set above is scoped instead by the complement block below.
    files: TYPED,
    ignores: NOT_TYPED,
    rules: {
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'error',
      // Not in strictTypeChecked -- only in configs.all -- so it has to be named. Left at the v8
      // default because considerDefaultExhaustiveForUnions counts any `default:` as exhaustive,
      // which would let a switch drift back to a catch-all without the rule noticing.
      '@typescript-eslint/switch-exhaustiveness-check': 'error',
      '@typescript-eslint/return-await': ['error', 'error-handling-correctness-only'],
      '@typescript-eslint/no-unnecessary-template-expression': 'error',
      // Held back in #171 because four of its six hits were two type lies -- shots.ts's parameter
      // and the index access behind CalibrationPanel's activeProbe -- where deleting the
      // conversion would have been the wrong fix.
      '@typescript-eslint/no-unnecessary-type-conversion': 'error',
      // `void expr` is how this repo marks a deliberately unawaited promise; this fails the idiom
      // applied to something that is not one.
      '@typescript-eslint/no-meaningless-void-operator': 'error',
      '@typescript-eslint/no-deprecated': [
        'error',
        {
          // Deliberate: the LAN proxy in front of the issuer is plain HTTP, and upstream's own
          // deprecation note sanctions exactly this use. Allowlisted here rather than disabled at
          // the call site, so the repo keeps zero inline directives.
          allow: [{ from: 'package', package: 'openid-client', name: 'allowInsecureRequests' }]
        }
      ]
    }
  },

  {
    // 14 mock stubs -- publish, fetch, loadDevSnapshot, publishOsDiscovery -- that must be async to
    // satisfy the interface they stand in for, which the rule cannot see. Not a blanket pass: the
    // one test that was merely async for no reason is fixed rather than covered by this.
    files: ['tests/**'],
    rules: { '@typescript-eslint/require-await': 'off' }
  },

  {
    // The complement of TYPED, written as one so the two sets cannot drift apart: a file added
    // outside src/ or tests/ lands here and goes un-type-checked, rather than falling through both
    // lists and being silently unenforced. Nothing below this may switch a type-aware rule back on
    // for these files. (no-explicit-any is not among the 61 it disables, and ts.configs.recommended
    // sets that one repo-wide already, so it stays on here.)
    files: ['**/*'],
    ignores: TYPED,
    extends: [ts.configs.disableTypeChecked]
  },

  // The service worker is inside TYPED's globs but outside the program, so the block above skips
  // it. Named here so every file lands in exactly one half.
  { files: NOT_TYPED, extends: [ts.configs.disableTypeChecked] },

  {
    files: ['**/*.ts', '**/*.js', '**/*.mjs', '**/*.svelte'],
    plugins: { local: { rules: { 'spdx-header': spdxHeader } } },
    rules: { 'local/spdx-header': 'error' }
  },

  {
    // The default is 'warn', and ESLint exits 0 on warnings.
    linterOptions: { reportUnusedDisableDirectives: 'error' }
  },

  // Last, so nothing re-enables a rule it turns off.
  prettier
);
