// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Daniel Snider

import { defineConfig, globalIgnores } from 'eslint/config';
import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import prettier from 'eslint-config-prettier';
import svelteConfig from './svelte.config.js';

const SVELTE = ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'];

// tsconfig's `include`, minus the .svelte half that the SVELTE block already covers.
const TYPED_TS = ['src/**/*.ts', 'tests/**/*.ts', 'vite.config.ts'];

// Outside tsconfig's `include`, so there is no type information for these at all -- not a rule
// exemption, an absent program. #132 is the issue that moves e2e/ into one.
const UNTYPED = [
  'e2e/**/*.ts',
  'e2e/**/*.mjs',
  'scripts/**/*.mjs',
  'playwright.config.ts',
  'svelte.config.js',
  'prettier.config.js',
  'eslint.config.js'
];

// No published header plugin can enforce this on components, because svelte-eslint-parser drops
// comments that sit outside <script>/<style> and so never reports the <!-- --> form.
const spdxHeader = {
  meta: {
    type: 'problem',
    docs: { description: 'require the two-line SPDX header from CONTRIBUTING.md' },
    schema: []
  },
  create(context) {
    return {
      Program(node) {
        // Four lines, not one, because a shebang legitimately precedes the header.
        const head = context.sourceCode.getText().split('\n').slice(0, 4).join('\n');
        const svelteFile = context.filename.endsWith('.svelte');
        const license = svelteFile
          ? /^<!-- SPDX-License-Identifier: AGPL-3\.0-or-later -->$/m
          : /^\/\/ SPDX-License-Identifier: AGPL-3\.0-or-later$/m;
        const copyright = svelteFile
          ? /^<!-- Copyright \(C\) \d{4} .+ -->$/m
          : /^\/\/ Copyright \(C\) \d{4} .+$/m;
        if (!license.test(head) || !copyright.test(head)) {
          context.report({
            node,
            message:
              'Missing the two-line SPDX header (CONTRIBUTING.md); components use the <!-- --> form.'
          });
        }
      }
    };
  }
};

export default defineConfig(
  // Flat config ignores only node_modules and .git by default, and reads no gitignore at all, so
  // .claude/ -- two live worktrees excluded merely by .git/info/exclude -- has to be named here.
  globalIgnores([
    '.claude/**',
    '.svelte-kit/**',
    'build/**',
    'build-recorder/**',
    'coverage/**',
    'playwright-report/**',
    'test-results/**',
    '.playwright/**',
    '.playwright-mcp/**',
    '.pnpm-cache/**',
    '.pnpm-data/**',
    '.pnpm-state/**',
    'data/**',
    'static/**',
    // Generated: an esbuild bundle whose own header says do not edit.
    'design/mission-control/support.js',
    // Regenerated by scripts/sanitize-fixture.mjs on every capture.
    'e2e/fixtures/live-snapshot.ts'
  ]),

  js.configs.recommended,
  ts.configs.recommended,

  // Scoped, because the preset puts no `files` key on its rule block and would otherwise run all
  // 35 svelte/* rules against plain .ts as well.
  { files: SVELTE, extends: [svelte.configs.recommended, svelte.configs.prettier] },

  {
    languageOptions: { globals: { ...globals.browser, ...globals.node } }
  },

  {
    files: SVELTE,
    languageOptions: {
      parserOptions: {
        parser: ts.parser,
        extraFileExtensions: ['.svelte'],
        svelteConfig,
        projectService: true
      }
    }
  },

  {
    // Deliberately not set at the root: the parser fails a file it cannot find in the project
    // outright rather than degrading, so turning this on globally makes all 20 files under
    // e2e/, scripts/ and the repo root report `Parsing error: ... not found by the project service`.
    files: TYPED_TS,
    languageOptions: { parserOptions: { projectService: true } }
  },

  {
    // typescript-eslint's own eslint-recommended block is scoped to .ts and never reaches .svelte,
    // so the core rules TypeScript already covers stay on across 12,787 lines of components.
    files: SVELTE,
    rules: {
      'constructor-super': 'off',
      'getter-return': 'off',
      'no-class-assign': 'off',
      'no-const-assign': 'off',
      'no-dupe-args': 'off',
      'no-dupe-class-members': 'off',
      'no-dupe-keys': 'off',
      'no-func-assign': 'off',
      'no-import-assign': 'off',
      'no-new-native-nonconstructor': 'off',
      'no-obj-calls': 'off',
      'no-redeclare': 'off',
      'no-setter-return': 'off',
      'no-this-before-super': 'off',
      'no-undef': 'off',
      'no-unreachable': 'off',
      'no-unsafe-negation': 'off',
      'no-with': 'off',
      // Not the core rule: it would tell you to make a never-reassigned `let x = $state(0)` const.
      'svelte/prefer-const': [
        'error',
        { excludedRunes: ['$props', '$derived', '$state', '$bindable'] }
      ]
    }
  },

  {
    // AGENTS.md's Svelte 5 guardrail is prose only, and eslint-plugin-svelte has no rule for these
    // three. `export let` and `$:` are compile errors under `runes: true`; bare-let is only the
    // `non_reactive_update` warning, which is why `check` runs with --fail-on-warnings.
    files: SVELTE,
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "SvelteDirective[kind='EventHandler']",
          message: 'Svelte 4 event directive. Use the onclick={fn} attribute form (AGENTS.md).'
        },
        {
          selector: "SvelteElement[name.name='slot']",
          message: 'Svelte 4 slot. Use {#snippet} + {@render children()} (AGENTS.md).'
        }
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'svelte',
              importNames: ['createEventDispatcher'],
              message: 'Svelte 4 component events. Use callback props (AGENTS.md).'
            }
          ]
        }
      ],
      // Both ship as warnings and both measure zero, so promoting them keeps the config warning-free.
      'svelte/no-at-debug-tags': 'error',
      'svelte/no-inspect': 'error',
      // Every link here is a correct root-relative literal and no kit.paths.base is configured.
      'svelte/no-navigation-without-resolve': 'off',
      // Checks mutability alone, with no notion of reactive scope, so it flags function-local
      // scratch Maps and Sets that are rebuilt per call and never held as state.
      'svelte/prefer-svelte-reactivity': 'off',
      // A `{' x '}` literal is how you pin whitespace that Prettier's re-wrapping would otherwise
      // move into an indent, so the mustache the rule calls useless is load-bearing.
      'svelte/no-useless-mustaches': 'off'
    }
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
      ]
    }
  },

  {
    // Scoped, never universal: every rule here calls getParserServices, which throws rather than
    // degrading when a file carries no type information. Widens with each commit of #165; the
    // endpoint is TYPED_TS plus src/**/*.svelte.
    files: ['src/routes/**/*.ts', 'src/routes/**/*.svelte'],
    rules: {
      '@typescript-eslint/no-unsafe-argument': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-unsafe-enum-comparison': 'error',
      '@typescript-eslint/no-unsafe-unary-minus': 'error'
    }
  },

  {
    // Nothing below this may switch a type-aware rule back on for these files.
    files: UNTYPED,
    extends: [ts.configs.disableTypeChecked]
  },

  {
    // Syntactic, so it needs no program and can go on everywhere. It is what stops a future `: any`
    // being used to silence one of the seven rules above.
    rules: { '@typescript-eslint/no-explicit-any': 'error' }
  },

  {
    files: ['**/*.ts', '**/*.js', '**/*.mjs', '**/*.svelte'],
    plugins: { local: { rules: { 'spdx-header': spdxHeader } } },
    rules: { 'local/spdx-header': 'error' }
  },

  {
    // The default is 'warn', and ESLint exits 0 on warnings.
    linterOptions: { reportUnusedDisableDirectives: 'error' }
  },

  // Last, so nothing re-enables a rule it turns off.
  prettier
);
