name: Build and Publish grow-app Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'src/**'
      - 'static/**'
      - 'svelte.config.js'
      - 'vite.config.ts'
      - '.github/workflows/build.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'src/**'
      - 'static/**'
      - 'svelte.config.js'
      - 'vite.config.ts'
      - '.github/workflows/build.yaml'

jobs:
  build:
    uses: dephekt/ci-templates/.github/workflows/docker-build.yml@main
    permissions:
      contents: read
      packages: write
    with:
      image_name: ghcr.io/dephekt/grow-app
      upstream_image_search: docker.io/node
      upstream_name_short: node
